# 训练配置

# 数据集配置
data:
  train_dataset: DIV2K
  train_dir: ./data/datasets/DIV2K/train
  val_dataset: DIV2K100
  val_dir: ./data/datasets/DIV2K/val
  patch_size: 24
  batch_size: 2  # 减小批次大小
  num_workers: 2
  augment: true
  pin_memory: true  # 启用pin_memory以加速数据加载
  prefetch_factor: 2  # 预加载因子

# 模型配置
model:
  encoder: EDSR-b  # 可选: EDSR-b, RDN, SwinIR
  latent_dim: 64
  render_dim: 24
  n_heads: 4
  n_layers: 4

# 训练配置
train:
  lr: 1.0e-4
  min_lr: 1.0e-7
  weight_decay: 0.0
  epochs: 1000
  save_every: 10
  val_every: 10  # 增加验证间隔
  val_samples: 5  # 每次验证的样本数量
  resume: false
  checkpoint: null
  gradient_accumulation_steps: 4  # 梯度累积步数
  max_grad_norm: 1.0  # 梯度裁剪阈值
  empty_cache_freq: 32  # 每处理多少个批次清理一次缓存

# 优化器配置
optimizer:
  type: Adam
  beta1: 0.9
  beta2: 0.999

# 学习率调度器
scheduler:
  type: CosineAnnealingLR
  T_max: 1000

# 损失函数配置
loss:
  type: L1
  perceptual_weight: 0.1
  adversarial_weight: 0.005

# 日志配置
log:
  tensorboard_dir: ./logs/tensorboard
  save_dir: ./logs/checkpoints
  log_memory: true  # 是否记录内存使用情况 